services:
  ambassador-be: 
    container_name: ambassador-be
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - ambassador-db

  ambassador-db:
    image: mysql:8.0.33
    container_name: ambassador-db
    tty: true
    restart: unless-stopped
    ports:
      - '33066:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ambassador-db
      MYSQL_USER: ambassador-db
      MYSQL_PASSWORD: Password123
    volumes:
      - ./docker/mysql:/var/lib/mysql

